name: pabtugasuas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_database: ^11.3.6
  firebase_auth: 5.5.4
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  intl: ^0.20.2
  foundation: ^0.0.5
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.1.2
  image: ^4.5.4
  geolocator: ^9.0.1 # To get location coordinates
  geocoding: ^2.0.4 # To get address from coordinates
  google_maps_flutter: ^2.12.2
  latlong2: ^0.9.1
  flutter_map: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/preloved_logo.png  # Pastikan ini ada dan sesuai dengan path gambar
